name: James Peterson Cinematography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1a21'
    - '#3b324f'
    - '#ffffff'
    - '#695d83'
    - '#e0d5ee'
  brandStrength: 0.625
  lightness: 0.637349154567346
  saturation: 0.28129798360168934
  rhythmicContrast: 0.9060119306668639
purpose: []
